#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'vim'
cookbook 'rubygems'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'git'
cookbook 'varnish'
cookbook 'apache'