invalid8r : 
  - sitekey : stylelist
    host : www.stylelist.com
    services : 
      - name : varnish
        instances :
          - url : ec2-54-235-239-128.compute-1.amazonaws.com
            port : 80
          - url : ec2-184-72-83-136.compute-1.amazonaws.com
            port : 80